name: Docs
on:
  push:
    branches:
    - master
    paths:
    - 'docs/**'

jobs:
  copyto:
    name: Copy docs
    runs-on: ubuntu-latest
    
    steps:
    - name: Copy to
      uses: leogr/copyto-action@v0.1.0
      env:
        DST_REPO: vchain-us/docs
        DST_PATH: site/vcn
        SRC_PATH: docs
        GH_PAT: ${{ secrets.GH_PAT }}
