name: CodeNotary

on:
  push:
    tags:        
      - v*

jobs:
  verify-commit:

    runs-on: ubuntu-latest
    
    steps:
     - name: Checkout
       uses: actions/checkout@master
     
     - name: Verify
       uses: vchain-us/verify-action@master